---
- name: Playbook to deploy openVPN server
  hosts: frontenda
  gather_facts: true
  tasks:
    - name: Install OpenVPN and Easy-RSA.
      apt:
        name:
          - openvpn
          - easy-rsa
        state: present
        update_cache: true

    - name: Copy config file to /etc.
      ansible.builtin.copy:
        src: /usr/share/doc/openvpn/examples/sample-config-files/server.conf
        dest: /etc/openvpn
        remote_src: yes

    - name: Modify port config.
      lineinfile:
        path: /etc/openvpn/server.conf
        regexp: '^port'
        line: 'port 1194'

    - name: Modify protocol config.
      lineinfile:
        path: /etc/openvpn/server.conf
        regexp: '^proto'
        line: "proto udp"

    - name: Point subnet for cliet trafic config.
      lineinfile:
        path: /etc/openvpn/server.conf
        regexp: '^push'
        line: 'push "route "10.0.0.0 255.255.0.0"'

    - name: Enable IP forwarding.
      lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv4.ip_forward = 1'
    
    - name: Apply changes.
      command: sysctl -p
