---
- name: Playbook to deploy tomcat
  hosts: frontend
  gather_facts: true
  vars_files:
    - credentials.yml
  tasks:
    - name: Display the password.
      debug:
        var: password

    - name: Install requirements packages.
      apt:
        name:
          - openjdk-17-jdk
          - curl
          - wget
          - tar
          - bash-completion
        state: present
        update_cache: true

    - name: java version.
      command: java -version
      register: java_version
      ignore_errors: true
    
    - name: Display java version.
      debug:
        var: java_version
      ignore_errors: true

    - name: Add group "{{ GROUP_NAME }}"
      ansible.builtin.group:
        name: "{{ GROUP_NAME }}"
        state: present

    - name: Add user "{{ USER_NAME }}"
      ansible.builtin.user:
        name: "{{ USER_NAME }}"
        state: present
        group: "{{ GROUP_NAME }}"

    - name: Download tomcat tar.
      ansible.builtin.get_url:
        url: "{{ URL_TOMCAT }}"
        dest: /tmp

    - name: Unarchive the file.
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-10.1.34.tar.gz
        dest: /usr/local
        remote_src: yes
        owner: "{{ USER_NAME }}"
        group: "{{ GROUP_NAME }}"
    
    - name: Rename the extracted directory
      ansible.builtin.command:
        cmd: mv /usr/local/apache-tomcat-10.1.34 /usr/local/tomcat10
    
    - name: Give permission.
      ansible.builtin.file:
        path: /usr/local/tomcat10/bin
        recurse: yes
        owner: "{{ USER_NAME }}"
        group: "{{ GROUP_NAME }}"
        mode: u=rwx,g=rwx

    - name: Create service file for systemd.
      blockinfile:
        path: /etc/systemd/system/tomcat.service 
        create: true
        block: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          User=tomcat
          Group=tomcat

          Environment="JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64"
          Environment="CATALINA_PID=/usr/local/tomcat10/temp/tomcat.pid"
          Environment="CATALINA_HOME=/usr/local/tomcat10"
          Environment="CATALINA_BASE=/usr/local/tomcat10"
          Environment="CATALINA_OPTS=-Xms212M -Xmx512M -server -XX:+UseParallelGC"
          Environment="JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom"

          ExecStart=/usr/local/tomcat10/bin/startup.sh
          ExecStop=/usr/local/tomcat10/bin/shutdown.sh

          [Install]
          WantedBy=multi-user.target
    
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: permissive
      when: ansible_facts['distribution'] == "RedHat"

    - name: Restart service tomcat on redhat, in all cases, also issue daemon-reload to pick up config changes
      ansible.builtin.systemd_service:
        state: started
        daemon_reload: true
        enabled: true
        name: tomcat







    
